//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_arqueocaja_det
    {
        public int idArqueoCaja_Det { get; set; }
        public int idArqueoCaja { get; set; }
        public int idmoneda { get; set; }
        public int idDenominacion { get; set; }
        public decimal cantidad { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual tbl_arqueocaja tbl_arqueocaja { get; set; }
        public virtual tbl_denominacion tbl_denominacion { get; set; }
        public virtual tbl_moneda tbl_moneda { get; set; }
    }
}
