//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_listaprecio
    {
        public int id_listaprecio_det { get; set; }
        public string nombre { get; set; }
        public string producto { get; set; }
        public double precio_venta { get; set; }
        public int id_listaprecio { get; set; }
        public int id_producto { get; set; }
    }
}
